export const CURRENCIES = [
  { code: "RUB", name: "Российский рубль", symbol: "₽" },
  { code: "USD", name: "Доллар США", symbol: "$" },
  { code: "EUR", name: "Евро", symbol: "€" },
  { code: "GBP", name: "Фунт стерлингов", symbol: "£" },
  { code: "CHF", name: "Швейцарский франк", symbol: "₣" },
  { code: "JPY", name: "Японская иена", symbol: "¥" },
  { code: "CNY", name: "Китайский юань", symbol: "¥" },
  { code: "KRW", name: "Корейская вона", symbol: "₩" },
  { code: "INR", name: "Индийская рупия", symbol: "₹" },
  { code: "VND", name: "Вьетнамский донг", symbol: "₫" },
  { code: "THB", name: "Тайский бат", symbol: "฿" },
  { code: "SGD", name: "Сингапурский доллар", symbol: "S$" },
  { code: "MYR", name: "Малайзийский ринггит", symbol: "RM" },
  { code: "ILS", name: "Израильский шекель", symbol: "₪" },
  { code: "AED", name: "Дирхам ОАЭ", symbol: "د.إ" },
  { code: "SAR", name: "Саудовский риал", symbol: "﷼" },
  { code: "TRY", name: "Турецкая лира", symbol: "₺" },
  { code: "UAH", name: "Украинская гривна", symbol: "₴" },
  { code: "KZT", name: "Казахстанский тенге", symbol: "₸" },
  { code: "BYN", name: "Белорусский рубль", symbol: "Br" },
  { code: "GEL", name: "Грузинский лари", symbol: "₾" },
  { code: "AMD", name: "Армянский драм", symbol: "֏" },
  { code: "AZN", name: "Азербайджанский манат", symbol: "₼" },
  { code: "PLN", name: "Польский злотый", symbol: "zł" },
  { code: "CZK", name: "Чешская крона", symbol: "Kč" },
  { code: "SEK", name: "Шведская крона", symbol: "kr" },
  { code: "NOK", name: "Норвежская крона", symbol: "kr" },
  { code: "DKK", name: "Датская крона", symbol: "kr" },
  { code: "CAD", name: "Канадский доллар", symbol: "C$" },
  { code: "AUD", name: "Австралийский доллар", symbol: "A$" },
  { code: "NZD", name: "Новозеландский доллар", symbol: "NZ$" },
  { code: "BRL", name: "Бразильский реал", symbol: "R$" },
  { code: "MXN", name: "Мексиканское песо", symbol: "$" },
  { code: "ARS", name: "Аргентинское песо", symbol: "$" },
  { code: "ZAR", name: "Южноафриканский рэнд", symbol: "R" },
  { code: "EGP", name: "Египетский фунт", symbol: "E£" },
  { code: "HKD", name: "Гонконгский доллар", symbol: "HK$" },
  { code: "TWD", name: "Тайваньский доллар", symbol: "NT$" },
  { code: "PHP", name: "Филиппинское песо", symbol: "₱" },
  { code: "IDR", name: "Индонезийская рупия", symbol: "Rp" },
  { code: "PKR", name: "Пакистанская рупия", symbol: "₨" },
];

export const getCurrencySymbol = (code: string): string => {
  return CURRENCIES.find((c) => c.code === code)?.symbol || code;
};

