export const CURRENCIES = [
  // ── Популярные / СНГ ──────────────────────────
  { code: "RUB", name: "Российский рубль", symbol: "₽" },
  { code: "USD", name: "Доллар США", symbol: "$" },
  { code: "EUR", name: "Евро", symbol: "€" },
  { code: "GBP", name: "Фунт стерлингов", symbol: "£" },
  { code: "CHF", name: "Швейцарский франк", symbol: "Fr" },
  { code: "UAH", name: "Украинская гривна", symbol: "₴" },
  { code: "KZT", name: "Казахстанский тенге", symbol: "₸" },
  { code: "BYN", name: "Белорусский рубль", symbol: "Br" },
  { code: "GEL", name: "Грузинский лари", symbol: "₾" },
  { code: "AMD", name: "Армянский драм", symbol: "֏" },
  { code: "AZN", name: "Азербайджанский манат", symbol: "₼" },
  { code: "UZS", name: "Узбекский сум", symbol: "сўм" },
  { code: "KGS", name: "Киргизский сом", symbol: "С" },
  { code: "TJS", name: "Таджикский сомони", symbol: "SM" },
  { code: "TMT", name: "Туркменский манат", symbol: "T" },
  { code: "MDL", name: "Молдавский лей", symbol: "L" },

  // ── Европа ────────────────────────────────────
  { code: "SEK", name: "Шведская крона", symbol: "kr" },
  { code: "NOK", name: "Норвежская крона", symbol: "kr" },
  { code: "DKK", name: "Датская крона", symbol: "kr" },
  { code: "PLN", name: "Польский злотый", symbol: "zł" },
  { code: "CZK", name: "Чешская крона", symbol: "Kč" },
  { code: "HUF", name: "Венгерский форинт", symbol: "Ft" },
  { code: "RON", name: "Румынский лей", symbol: "lei" },
  { code: "BGN", name: "Болгарский лев", symbol: "лв" },
  { code: "RSD", name: "Сербский динар", symbol: "дин." },
  { code: "BAM", name: "Боснийская марка", symbol: "KM" },
  { code: "ALL", name: "Албанский лек", symbol: "L" },
  { code: "MKD", name: "Македонский денар", symbol: "ден" },
  { code: "ISK", name: "Исландская крона", symbol: "kr" },
  { code: "TRY", name: "Турецкая лира", symbol: "₺" },

  // ── Северная Америка ──────────────────────────
  { code: "CAD", name: "Канадский доллар", symbol: "C$" },

  // ── Латинская Америка ─────────────────────────
  { code: "BRL", name: "Бразильский реал", symbol: "R$" },
  { code: "MXN", name: "Мексиканское песо", symbol: "MX$" },
  { code: "ARS", name: "Аргентинское песо", symbol: "AR$" },
  { code: "COP", name: "Колумбийское песо", symbol: "CO$" },
  { code: "CLP", name: "Чилийское песо", symbol: "CL$" },
  { code: "PEN", name: "Перуанский соль", symbol: "S/" },
  { code: "UYU", name: "Уругвайское песо", symbol: "$U" },
  { code: "PYG", name: "Парагвайский гуарани", symbol: "₲" },
  { code: "BOB", name: "Боливийский боливиано", symbol: "Bs" },
  { code: "VES", name: "Венесуэльский боливар", symbol: "Bs.S" },
  { code: "CRC", name: "Костариканский колон", symbol: "₡" },
  { code: "GTQ", name: "Гватемальский кетсаль", symbol: "Q" },
  { code: "HNL", name: "Гондурасская лемпира", symbol: "L" },
  { code: "NIO", name: "Никарагуанская кордоба", symbol: "C$" },
  { code: "PAB", name: "Панамский бальбоа", symbol: "B/" },
  { code: "DOP", name: "Доминиканское песо", symbol: "RD$" },
  { code: "CUP", name: "Кубинское песо", symbol: "₱" },
  { code: "HTG", name: "Гаитянский гурд", symbol: "G" },
  { code: "JMD", name: "Ямайский доллар", symbol: "J$" },
  { code: "TTD", name: "Доллар Тринидада и Тобаго", symbol: "TT$" },
  { code: "BBD", name: "Барбадосский доллар", symbol: "Bds$" },
  { code: "BSD", name: "Багамский доллар", symbol: "B$" },
  { code: "BZD", name: "Белизский доллар", symbol: "BZ$" },
  { code: "GYD", name: "Гайанский доллар", symbol: "GY$" },
  { code: "SRD", name: "Суринамский доллар", symbol: "SR$" },
  { code: "AWG", name: "Арубанский флорин", symbol: "Afl" },
  { code: "ANG", name: "Нидерландский антильский гульден", symbol: "NAf" },
  { code: "KYD", name: "Доллар Каймановых островов", symbol: "CI$" },
  { code: "BMD", name: "Бермудский доллар", symbol: "BD$" },
  { code: "XCD", name: "Восточнокарибский доллар", symbol: "EC$" },

  // ── Ближний Восток ────────────────────────────
  { code: "AED", name: "Дирхам ОАЭ", symbol: "د.إ" },
  { code: "SAR", name: "Саудовский риял", symbol: "﷼" },
  { code: "QAR", name: "Катарский риял", symbol: "﷼" },
  { code: "KWD", name: "Кувейтский динар", symbol: "د.ك" },
  { code: "BHD", name: "Бахрейнский динар", symbol: "BD" },
  { code: "OMR", name: "Оманский риал", symbol: "﷼" },
  { code: "JOD", name: "Иорданский динар", symbol: "JD" },
  { code: "ILS", name: "Израильский шекель", symbol: "₪" },
  { code: "IQD", name: "Иракский динар", symbol: "ع.د" },
  { code: "IRR", name: "Иранский риал", symbol: "﷼" },
  { code: "SYP", name: "Сирийский фунт", symbol: "£S" },
  { code: "LBP", name: "Ливанский фунт", symbol: "L£" },
  { code: "YER", name: "Йеменский риал", symbol: "﷼" },

  // ── Восточная Азия ────────────────────────────
  { code: "JPY", name: "Японская иена", symbol: "¥" },
  { code: "CNY", name: "Китайский юань", symbol: "¥" },
  { code: "KRW", name: "Южнокорейская вона", symbol: "₩" },
  { code: "TWD", name: "Тайваньский доллар", symbol: "NT$" },
  { code: "HKD", name: "Гонконгский доллар", symbol: "HK$" },
  { code: "MOP", name: "Патака Макао", symbol: "MOP$" },
  { code: "MNT", name: "Монгольский тугрик", symbol: "₮" },
  { code: "KPW", name: "Северокорейская вона", symbol: "₩" },

  // ── Южная Азия ────────────────────────────────
  { code: "INR", name: "Индийская рупия", symbol: "₹" },
  { code: "PKR", name: "Пакистанская рупия", symbol: "₨" },
  { code: "LKR", name: "Шри-Ланкийская рупия", symbol: "Rs" },
  { code: "BDT", name: "Бангладешская така", symbol: "৳" },
  { code: "NPR", name: "Непальская рупия", symbol: "₨" },
  { code: "MVR", name: "Мальдивская руфия", symbol: "Rf" },
  { code: "BTN", name: "Бутанский нгултрум", symbol: "Nu" },
  { code: "AFN", name: "Афганский афгани", symbol: "؋" },

  // ── Юго-Восточная Азия ────────────────────────
  { code: "THB", name: "Тайский бат", symbol: "฿" },
  { code: "VND", name: "Вьетнамский донг", symbol: "₫" },
  { code: "SGD", name: "Сингапурский доллар", symbol: "S$" },
  { code: "MYR", name: "Малайзийский ринггит", symbol: "RM" },
  { code: "IDR", name: "Индонезийская рупия", symbol: "Rp" },
  { code: "PHP", name: "Филиппинское песо", symbol: "₱" },
  { code: "MMK", name: "Мьянманский кьят", symbol: "K" },
  { code: "KHR", name: "Камбоджийский риель", symbol: "៛" },
  { code: "LAK", name: "Лаосский кип", symbol: "₭" },
  { code: "BND", name: "Брунейский доллар", symbol: "B$" },

  // ── Океания ───────────────────────────────────
  { code: "AUD", name: "Австралийский доллар", symbol: "A$" },
  { code: "NZD", name: "Новозеландский доллар", symbol: "NZ$" },
  { code: "FJD", name: "Фиджийский доллар", symbol: "FJ$" },
  { code: "PGK", name: "Кина Папуа — Новой Гвинеи", symbol: "K" },
  { code: "WST", name: "Самоанская тала", symbol: "WS$" },
  { code: "TOP", name: "Тонганская паанга", symbol: "T$" },
  { code: "VUV", name: "Вануатский вату", symbol: "VT" },
  { code: "SBD", name: "Доллар Соломоновых Островов", symbol: "SI$" },
  { code: "XPF", name: "Франк КФП", symbol: "₣" },

  // ── Африка — Север ────────────────────────────
  { code: "EGP", name: "Египетский фунт", symbol: "E£" },
  { code: "MAD", name: "Марокканский дирхам", symbol: "MAD" },
  { code: "TND", name: "Тунисский динар", symbol: "DT" },
  { code: "DZD", name: "Алжирский динар", symbol: "د.ج" },
  { code: "LYD", name: "Ливийский динар", symbol: "ل.د" },
  { code: "SDG", name: "Суданский фунт", symbol: "£SD" },

  // ── Африка — Запад ────────────────────────────
  { code: "NGN", name: "Нигерийская найра", symbol: "₦" },
  { code: "GHS", name: "Ганский седи", symbol: "GH₵" },
  { code: "XOF", name: "Франк КФА (BCEAO)", symbol: "CFA" },
  { code: "CVE", name: "Эскудо Кабо-Верде", symbol: "Esc" },
  { code: "GMD", name: "Гамбийский даласи", symbol: "D" },
  { code: "GNF", name: "Гвинейский франк", symbol: "FG" },
  { code: "LRD", name: "Либерийский доллар", symbol: "L$" },
  { code: "SLE", name: "Сьерра-леонский леоне", symbol: "Le" },
  { code: "MRU", name: "Мавританская угия", symbol: "UM" },

  // ── Африка — Восток ───────────────────────────
  { code: "KES", name: "Кенийский шиллинг", symbol: "KSh" },
  { code: "TZS", name: "Танзанийский шиллинг", symbol: "TSh" },
  { code: "UGX", name: "Угандийский шиллинг", symbol: "USh" },
  { code: "ETB", name: "Эфиопский быр", symbol: "Br" },
  { code: "RWF", name: "Руандийский франк", symbol: "RF" },
  { code: "BIF", name: "Бурундийский франк", symbol: "FBu" },
  { code: "DJF", name: "Джибутийский франк", symbol: "Fdj" },
  { code: "ERN", name: "Эритрейская накфа", symbol: "Nfk" },
  { code: "SOS", name: "Сомалийский шиллинг", symbol: "Sh" },
  { code: "MGA", name: "Малагасийский ариари", symbol: "Ar" },
  { code: "MUR", name: "Маврикийская рупия", symbol: "₨" },
  { code: "SCR", name: "Сейшельская рупия", symbol: "₨" },
  { code: "KMF", name: "Коморский франк", symbol: "CF" },
  { code: "SSP", name: "Южносуданский фунт", symbol: "£" },

  // ── Африка — Центр ────────────────────────────
  { code: "XAF", name: "Франк КФА (BEAC)", symbol: "FCFA" },
  { code: "CDF", name: "Конголезский франк", symbol: "FC" },
  { code: "STN", name: "Добра Сан-Томе и Принсипи", symbol: "Db" },

  // ── Африка — Юг ───────────────────────────────
  { code: "ZAR", name: "Южноафриканский рэнд", symbol: "R" },
  { code: "BWP", name: "Ботсванская пула", symbol: "P" },
  { code: "MWK", name: "Малавийская квача", symbol: "MK" },
  { code: "ZMW", name: "Замбийская квача", symbol: "ZK" },
  { code: "MZN", name: "Мозамбикский метикал", symbol: "MT" },
  { code: "AOA", name: "Ангольская кванза", symbol: "Kz" },
  { code: "NAD", name: "Намибийский доллар", symbol: "N$" },
  { code: "SZL", name: "Свазилендский лилангени", symbol: "E" },
  { code: "LSL", name: "Лесотский лоти", symbol: "M" },
];

export const getCurrencySymbol = (code: string): string => {
  return CURRENCIES.find((c) => c.code === code)?.symbol || code;
};
